In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import time

In [3]:
size = 1000000

pylist = list(range(size))
start = time.time()
sqr = [x**2 for x in pylist]
end = time.time()
print(f'Python list execution time {end - start} ')

arr = np.array(pylist)
start = time.time()
sqr_n = arr**2
end = time.time()
print(f'Numpy array execution time {end - start} ')


Python list execution time 0.09633255004882812 
Numpy array execution time 0.0019969940185546875 


In [5]:
#memory

import sys
print(f"python list size = {sys.getsizeof(pylist) * len(pylist)} bytes")
print(f"numpy list size = {arr.nbytes} bytes")

python list size = 8000056000000 bytes
numpy list size = 8000000 bytes


In [9]:
#create array from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [10]:
arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2) , arr2.dtype, arr2.shape) 

['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [12]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [24]:
#zero matrix
arr1 = np.zeros((2,3), dtype = 'int64' )
print(arr1)

arr1 = np.ones((5,), dtype = 'int64' )
print(arr1)

arr2 = np.full((2,3),50)
print(arr2)

arr3 = np.eye(4)
print(arr3)

arr4 = np.arange(1,10,2)
print(arr4)

arr5 = np.linspace(1,100,4)
print(arr5)

[[0 0 0]
 [0 0 0]]
[1 1 1 1 1]
[[50 50 50]
 [50 50 50]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[  1.  34.  67. 100.]


In [28]:
arr = np.array([[1,2,3],[4,5,6]])
               
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr) 

(2, 3)
6
2
int64
[[1. 2. 3.]
 [4. 5. 6.]]


In [36]:
new_arr = arr.reshape((3,2))
print(new_arr)

flat_arr = arr.flatten() #converts to 1 D array
print(flat_arr)

#indexing
print(new_arr[2][1])

#fancy indexing
idx = [0, 1, 3]
print(flat_arr[idx])

#boolean indexing 
print(flat_arr[flat_arr % 2 == 0])

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
6
[1 2 4]
[2 4 6]


In [38]:
#Slicing

print(flat_arr[1:5:2])
print(flat_arr[::-1])

[2 4]
[6 5 4 3 2 1]


In [5]:
list = [1,2,3,4]
sub_list = list[1:3]

sub_list[0] = 200
print(sub_list)
print(list)

arr = np.array(list)
sub_arr = arr[1:3].copy()
sub_arr[0] = 200
print(sub_arr)
print(arr)

[200, 3]
[1, 2, 3, 4]
[200   3]
[1 2 3 4]


In [17]:
#data types 
arr = np.array([1,2,3,4,"string"])
print(arr, arr.dtype)

c_arr = np.array([3+2j])
c2_arr = np.array([2+1j])
t_arr = c_arr + c2_arr
print(t_arr)

['1' '2' '3' '4' 'string'] <U21
[5.+3.j]


In [22]:
#Multi Dimesional Arrays 

mul_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mul_arr, mul_arr.shape)

print(np.sum(mul_arr))

print(np.sum(mul_arr, axis = 0))

print(mul_arr[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
45
[12 15 18]
[[2]
 [5]]


In [28]:
#3D Array 

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,9],[9,10],[11,12]]])
print(arr3d, arr3d.shape)

#indexing
print(arr3d[0,0,1])

#slicing
print(arr3d[:,1,:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  9]
  [ 9 10]
  [11 12]]] (2, 3, 2)
2
[[ 3  4]
 [ 9 10]]


In [29]:
#vectorization

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 ** 2)
print(arr1 + 10)
print(arr1 + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [34]:
#broadcasting

arrn = np.array([1,2,3,4,5])
print(arrn + 5)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1 + arr2)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [39]:
#Normalization 

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)

normalized_arr = (arr-mean)/std
print(normalized_arr)
mean = np.mean(normalized_arr)
std = np.std(normalized_arr)
print(mean)
print(std)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0


In [43]:
#mathematical function

#agregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0


In [44]:
#power fnx 

arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [52]:
#log

arr = np.array([1,2,3,4,5,6])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [51]:
#rounding 

print(np.round(3.13))
print(np.ceil(3.14))
print(np.floor(3.13))
print(np.trunc(3.14))
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-6  1  2  3  4  5  6]
[-6  1  2  3  4  5  6]
[1 2 3 4 5 6 6]
